// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/send": {
            "post": {
                "description": "Endpoint para enviar mensagens ao RabbitMQ. Requer uma mensagem e uma routing key válida. A mensagem será publicada no exchange configurado usando a routing key especificada.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Send Message RabbitMQ"
                ],
                "summary": "Envia uma mensagem para o RabbitMQ",
                "parameters": [
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_handlers.Payload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_handlers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_handlers.BadRequestError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pkg_handlers.BadRequestError": {
            "description": "Erro de requisição",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "message is required"
                }
            }
        },
        "pkg_handlers.Payload": {
            "description": "Payload da requisição",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "routing_key": {
                    "type": "string"
                }
            }
        },
        "pkg_handlers.Response": {
            "description": "Resposta da requisição",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "message sent"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "127.0.0.1:3000",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "RabbitMQ Simple",
	Description:      "Este é um projeto de exemplo que demonstra a implementação de um sistema de mensageria usando RabbitMQ e Go",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
