basePath: /
definitions:
  pkg_handlers.BadRequestError:
    description: Erro de requisição
    properties:
      error:
        example: message is required
        type: string
    type: object
  pkg_handlers.Payload:
    description: Payload da requisição
    properties:
      message:
        type: string
      routing_key:
        type: string
    type: object
  pkg_handlers.Response:
    description: Resposta da requisição
    properties:
      message:
        example: message sent
        type: string
    type: object
host: localhost:3000
info:
  contact:
    name: API Support
  description: Este é um projeto de exemplo que demonstra a implementação de um sistema
    de mensageria usando RabbitMQ e Go
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: RabbitMQ Simple
  version: 0.0.1
paths:
  /send:
    post:
      consumes:
      - application/json
      description: Endpoint para enviar mensagens ao RabbitMQ. Requer uma mensagem
        e uma routing key válida. A mensagem será publicada no exchange configurado
        usando a routing key especificada.
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/pkg_handlers.Payload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg_handlers.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_handlers.BadRequestError'
      summary: Envia uma mensagem para o RabbitMQ
      tags:
      - Send Message RabbitMQ
schemes:
- http
- https
swagger: "2.0"
