#!/bin/sh

echo "Running pre-commit hook"

echo "Running go mod tidy"
go mod tidy

echo "Running go fmt"
go fmt ./...

echo "Running go vet"
go vet ./...

echo "Running golangci-lint"
golangci-lint run ./...
