#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Verifica se há alterações staged
if git diff --cached --quiet; then
  echo "Nenhuma alteração para commit"
  exit 0
fi

echo "Running pre-commit hook"

echo "Running go mod tidy"
go mod tidy

echo "Running go fmt"
go fmt ./...

echo "Running go vet"
go vet ./...

echo "Running golangci-lint"
golangci-lint run ./...
